### ISSUE TITLE
Set command line arguments

### ISSUE THREAD

**Issue by bqtran** [ikappas/vscode-composer#5] opened 2018-01-11 19:43 UTC
It would be great if there was an configuration option to set additional command line arguments. I have an package that only works on linux (vend/resque) because it requires ext-pcntl, and composer isn't able to complete successfully without adding in an "--ignore-platform-reqs" on Windows (See https://github.com/composer/composer/issues/4584). I am currently running updates by hand to get around this issue.

Thanks.

**Comment by AnrDaemon** [comment] 2022-01-07 08:15
The problem is deeper than that.
I have a wrapper script that runs Composer executable through another wrapper script that runs specific version of PHP (I have all major versions from 5.6 onward installed and operable).
I was under impression that "executable" means that - what would be run directly to get the results, but it seems that's not quite true.

**Comment by ikappas** [comment] 2022-04-03 17:06
@bqtran Version 0.8.0 is out with several fixes including support for `composer.ignorePlatformReqs` setting, so I am closing this issue. Please feel free to reopen should you find that the issue still persists.

**Closed by ikappas** 2022-04-03 17:06 UTC
